version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - app.network
    environment:
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - app.network
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    command: sh -c './wait-for mysqldb:3306 -- npm start'

volumes:
  db:

networks:
  app.network:
    driver: bridge