spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: ''
        testWhileIdle: true
        url: jdbc:mysql://mysqldb:3306/products?useTimezone=true&serverTimezone=America/Sao_Paulo
        username: root
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
